### ISSUE TITLE
Bitcoin Reads Special: By Professor Per Bylund

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala/reading-club#9]

**Comment by rajarshimaitra** [comment]
@setusaurabh ping for the recording.

**Comment by VirdiJatin** [comment]
@paperpsych Ping for thumbnail

**Comment by VirdiJatin** [comment]
Bitcoin special Professor Per Bylund
00:10 - Introduction 
1:45 - Professor Per bylund go-through 
07:39 - The book project
13:13 - The Core ideas of Austrian economics (What is Austrian economics?)
20:34 - Introduction for Book
22:12 - QNA

**Comment by paperpsych** [comment]
@VirdiJatin 

![How to think about the Economy - Reading club](https://github.com/Bitshala/reading-club/assets/149538435/8e84372e-b2b4-47ef-b348-d8501e0479dd)

**Comment by VirdiJatin** [comment]
@rajarshimaitra here are questions you can listen to.. 

youtube link - https://www.youtube.com/watch?v=PcggxYAlVFg 
this video is private yet you can see description in which timelines are written for certain questuons.. and choose which question will be there for twitter shorts.

you can directly click on timelines to start video from that timestamp,  this will consume less time rather than seeing timelines and draging cursor here and there..

**Comment by rajarshimaitra** [comment]
@shreyanjoshi Ping for the video description and an Announcement tweet.

**Comment by VirdiJatin** [comment]
https://x.com/bitshala_org/status/1789262060364124581 

hey @rajarshimaitra, you can close this issue now!!

**Comment by rajarshimaitra** [comment]
Closed..
